name: type_translator
description: A library for parsing any type value.
version: 1.0.1
homepage: https://github.com/Arxing/dart-type_translator
author: Arxing <meiswind711108@gmail.com>
pubpage: https://pub.dev/packages/type_translator

environment:
  sdk: '>=2.4.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

#dev_dependencies:
#  pedantic: ^1.7.0
#  test: ^1.6.0
